### PR TITLE
Implemented methods to hit champions endpoint.

### PR DESCRIPTION
**Pull request by pcg79**
Implemented methods to access the `/champions` endpoint of the Riot API.

This includes tests.

What Faraday returns for the call is a bit different from the rest of the API calls.  It returns a Hashie of the form:

```
> response 
=> #<Hashie::Rash champions=[#<Hashie::Rash active=true attack_rank=8 bot_enabled=false bot_mm_enabled=false defense_rank=4 difficulty_rank=6 free_to_play=false id=266 magic_rank=3 name="Aatrox" ranked_play_enabled=true>,...
```

thus the call to `.champions` in `list`.

### CODE REVIEW

**Comment by petems** [comment]
Very nice! I was delaying implementing the `champions` stuff until I could figure out a good way of doing the free champions, this looks like a good way of handling it.

I'll add a few comments when I get back from work, but looks good overall! :+1:

**Comment by pcg79** [comment]
No problem.

**Comment by pcg79** [comment]
As a note as soon as I saw the Riot API I wanted to make a RubyGem out of it.  Then I searched GitHub and saw there were already 5 so I just picked one and started contributing.  Hope you don't mind. :)

I've got at least one more PR coming shortly to handle how Riot has implemented end point versioning.

**Comment by petems** [comment]
Cool :+1: 

Can you merge master into this? Rebase it if possible to keep the history clean :smile:

**Comment by pcg79** [comment]
This is good to go.

**Comment by petems** [comment]
Cool, I did a little tweak to fix the merge conflict and ordered alphabetically :+1:

**Pull request merged**
