### PR TITLE
Added myself as a contributor.

### PR DESCRIPTION
**Pull request by pcg79**
:)

### CODE REVIEW

**Comment by petems** [comment]
Cool, you wanna add your git contrib email to your Github account settings (the hungrymachine one)? 

Means the commits will link to your profile instead of showing the ghost thingy and you'll appear on the https://github.com/petems/riot_api/graphs/contributors page :+1:

**Comment by pcg79** [comment]
Ugh, have I been using my work email address this whole time?  Damn.

Ok, I added it.  Need to figure out if I can have a project-specific `.gitconfig` to use my personal address instead of work for this....

**Comment by petems** [comment]
https://github.com/blog/180-local-github-config or https://github.com/github/hub might be helpful :+1:

**Comment by pcg79** [comment]
Yup, that did it `git config user.email "..."`.  Ok, it should be using my personal email address now.  Not that I guess it matters that this point.  But it makes me happier.

**Pull request merged**
