### PR TITLE
Implemented summoner model.

### PR DESCRIPTION
**Pull request by pcg79**
Used virtus.  Worked well.  One thing I don't like about Virtus that I never noticed before is the lack of easy coercion.  For example, one of the fields the API returns is the date in milliseconds.  In Ruby you have to do

`Time.at millis / 1000.0`

but I can't see an easy way to do that in Virtus.  Not sure if that'll bite us in the ass later.

I'm rushing to finish before dinner so no tests yet.  I'll get to those tomorrow.

I did get cute w/ some meta programming on how to create the model object in each resource.  I'll make a separate PR for that since it might be a bit **too** cute. :)

### CODE REVIEW

**Comment by pcg79** [comment]
And I see this change broke the build.  Nooo!  That's what I get for rushing.

It's b/c `revision_date` is not implemented in the Virtus model due to the issue w/ coercion I mentioned above.

**Comment by petems** [comment]
Yeah, it's really weird it returns an epoch... but with 3 extra zeros for no reason?

**Comment by petems** [comment]
Weird, when I run the api through their javascript front end it returns an epoch without the zeros. Strange stuff.

**Comment by pcg79** [comment]
I'm an idiot.  Happens when I rush.  I have no idea why I was trying to convert the incoming `revision_date` to a `Time` object.  There's no reason for that.  So I just added it to the model as an `Integer` and we're all set.

Added a single simple test.  Nothing special.

For the record, I'm not married to the namespace `model` vs `models`.  But I stuck w/ the singular theme you already had going on with `resource`.

**Pull request merged**
